### ISSUE TITLE
Text truncated in filter dropdown in expenditure, receipts pages. 

### ISSUE THREAD

**Issue by shreyaagrawal0809** [CivicDataLab/fiscal_data_explorer_frontend#118]
<img width="377" alt="Screenshot 2022-10-08 at 12 35 05 PM" src="https://user-images.githubusercontent.com/35596028/194694764-2c1a8449-721b-4260-857e-acb4c108368b.png">

**Comment by shivamragnar** [comment]
@shreyaagrawal0809  
I think text truncated looks fine, we can add title text or tooltip on hover to show full text of these filters in the dropdown.
Please assign this to me i will fix this.

**Comment by shivamragnar** [comment]
[PR for this](https://github.com/CivicDataLab/hp-fiscal-data-explorer-frontend/pull/121)
