### ISSUE TITLE
Move the position of loading indicator to middle of the page in expenditure , schemes and receipts page

### ISSUE THREAD

**Issue by shreyaagrawal0809** [CivicDataLab/fiscal_data_explorer_frontend#120]
![image](https://user-images.githubusercontent.com/35596028/194699307-62eebf69-470a-40ca-bdd6-87e5957efb33.png)

**Comment by ShubhamShakyawal** [comment]
@shreyaagrawal0809 Please assign me. I would like to work on this

**Comment by shreyaagrawal0809** [comment]
Done @ShubhamShakyawal
